### ISSUE TITLE
Track Guests at Awfis events and include statistics in Sales Funnel 

### ISSUE THREAD

**Issue by gaurav-naik** [mntechnique/awfis_erpnext#1]
**Tasks:**
1. Create DocType Awfis Guest, with the following fields:
   -- Customer Name, Mobile No, EMail ID, Awfis Centre Visited
2. Override whitelisted method to include total count of Awfis Guests in Sales Funnel

**TAT**: 1.25 hr

**Comment by revant** [comment]
Corrections in Awfis Guest Doctype:
1. Validate Email
2. Disable Quick Edit for Awfis Guest Doctype

@bhamesh @gaurav-naik

**Comment by revant** [comment]
Set AG-###### or some naming series for awfis guest
@gaurav-naik @bhamesh 

Autoname, Roles part of SOP!!

**Comment by bhamesh** [comment]
1. Added email validation, naming series (AWFG.##### ) for Awfis Guest Doctype. 
2. Disabled quick entry for Awfis Guest Doctype.

Above two point done.
