### ISSUE TITLE
CRM: Visibility of Leads for Call Centre Team, Ops and Sales Team

### ISSUE THREAD

**Issue by gaurav-naik** [mntechnique/awfis_erpnext#4]
**Restrictions**

1. **Call Centre agent**
   1. Created By should reflect name of agent on Leads created via popup.
   2. Can View leads from own territory.
   3. Can Create leads in all territories.
   4. Lead created by agent should be auto-assigned to Regional Sales Manager for agent's territory.
2. **Ops Team member**
   1. Can View and Edit leads from own territory.
   2. Can View and Edit assigned leads from other territories.
   3. Lead created by Ops Team member to be auto-assigned to self.
3. **Sales Team member**
   1. Can View and Edit leads from own territory.
   2. Lead created by Sales Team member to be auto-assigned to self.

* Auto-assign to RSM: Employees will have to be created for ERPNext users who are RSMs beforehand.

**Comment by AnandAmitabh** [comment]
Restrictions:

**Call Centre Team** -
_Designation - Customer Support Officer_
i. Lead Owner: Agent ID or name should be captured in this field when lead is captured through pop-up
ii. Can view only those leads that are created by that particular user/agent
iii. No territory restriction on creation of leads
iv. Lead should get auto-assigned to the Regional Sales Manager of that territory

**Call Centre Team** -
_Designation - Manager - Call Centre_
i. Can create leads for all territories
ii. Can view leads created by all Call Centre agents ( Customer Support Officers)

**Operations** -
_Designation - Chief Operating Officer_
i. Can create, view and edit all leads, irrespective of territory
ii. Leads created must be auto assigned to the RSM of the territory

_Designation - Cluster Manager_
i. Can create, view, edit all leads for his particular territory
ii. Leads created must be auto assigned to the RSM of the territory

_Designations - Assistant Community Manager, Community Manager, Community Service Executive_
i. Can create, view and edit all leads for the particular centre to which they are assigned (**Centre field needs to be created in the Employee form**)
ii. All leads entered by these designations must be auto-assigned to the RSM for that territory

**Sales** -
_Designation - Head- Marketing_
i. Can create, view and edit all leads, irrespective of territory
ii. Leads created must be auto assigned to the RSM of the territory

_Designation - Regional Sales Manager_
i. Can create, view, edit all leads for the particular territory
ii. Leads created must be self - assigned

_Designation - Senior Manager-  Sales, Assistant Regional Sales Manager, Assistant Manager- Sales, Sales  Associate, Regional Manager - Meeting Room Sales, ARSM - Meeting Rooms, Manager- Sales_
i. Can create, view, edit all leads for the particular territory
ii. Leads created must be self - assigned

Across all designations and departments, the Lead Owner field should capture the name of the user/employee who is creating the lead

**Comment by gaurav-naik** [comment]
**Tasks:**
1. Modify popup endpoint: Set Owner, Created By of Lead to the agent to whom the popup is shown.
2. As per restrictions, auto-assign specific users to Lead OR Auto-share Lead with specific users.
3. Implement permission restrictions beyond user, role permissions. Include designations. 
4. Live testing.

**ETA**: 3 hrs.

**Comment by gaurav-naik** [comment]
**Implementation of Restrictions:**

*Restrictions by territory/centre will not apply when the user owns the Lead.

**Call Centre Team -**
_Designation - Customer Support Officer_
 i. Lead Owner: Agent ID or name should be captured in this field when lead is captured through pop-up.
```
- Handled under task 1
```

ii. Can view only those leads that are created by that particular user/agent.
```
- Role Permissions for Lead Doctype 
    > Apply User Permissions > Select Document Types > If Territory is permitted
- User Permissions on individual territories 
```
iii. No territory restriction on creation of leads.
```
- Handled under task 1. Lead Owner has no restrictions on creation of leads. 
```

iv. Lead should get auto-assigned to the Regional Sales Manager of that territory
```
- Handled under task 3
```

**Call Centre Team -**
_Designation - Manager - Call Centre_
i. Can create leads for all territories
```
- Role: Sales User
- Role Permissions for Lead Doctype 
   > Apply User Permissions > Select Document Types > If Territory is permitted
- User Permissions on individual territories
```
ii. Can view leads created by all Call Centre agents (Customer Support Officers)
```
- Role: Sales User
- Role Permissions for Lead Doctype 
    > Apply User Permissions > Select Document Types > If Territory is permitted
- User Permissions on individual territories
```
**Operations -**
_Designation - Chief Operating Officer_
i. Can create, view and edit all leads, irrespective of territory
```
- Role: Sales User
- Role Permissions for Lead Doctype 
    > Apply User Permissions > Select Document Types > If Territory is permitted
- User Permissions on individual territories
```
ii. Leads created must be auto assigned to the RSM of the territory
```
- Handled under task 3
```
_Designation - Cluster Manager_
i. Can create, view, edit all leads for his particular territory
```
- Role: Sales User
- Role Permissions for Lead Doctype 
    > Apply User Permissions > Select Document Types > If Territory is permitted
- User Permissions on individual territories
```
ii. Leads created must be auto assigned to the RSM of the territory
```
- Handled under task 3
```
_Designations - Assistant Community Manager, Community Manager, Community Service Executive_
i. Can create, view and edit all leads for the particular centre to which they are assigned (Centre field needs to be created in the Employee form)
```
- Role: Sales User
- Role Permissions for Lead Doctype 
    > Apply User Permissions > Select Document Types > If Awfis Centre is permitted
- User Permissions on Awfis Centres
```
ii. All leads entered by these designations must be auto-assigned to the RSM for that territory
```
- Handled under task 3
```

**Sales -**
_Designation - Head- Marketing_
i. Can create, view and edit all leads, irrespective of territory
```
- Role: Sales User
- No restrictions on Territory.
```
ii. Leads created must be auto assigned to the RSM of the territory
```
- Handled under Task 3
```
_Designation - Regional Sales Manager_
i. Can create, view, edit all leads for the particular territory
```
- Role: Sales User
- Role Permissions for Lead Doctype 
    > Apply User Permissions > Select Document Types > If Territory is permitted
- User Permissions on individual territories
```
ii. Leads created must be self - assigned
```
- Handled under Task 3
```
_Designation - Senior Manager- Sales, Assistant Regional Sales Manager, Assistant Manager- Sales, Sales Associate, Regional Manager - Meeting Room Sales, ARSM - Meeting Rooms, Manager- Sales_
i. Can create, view, edit all leads for the particular territory
```
- Role: Sales User
- Role Permissions for Lead Doctype 
    > Apply User Permissions > Select Document Types > If Territory is permitted
- User Permissions on individual territories
```
ii. Leads created must be self - assigned
```
- Handled under Task 3
```

**Comment by AnandAmitabh** [comment]
Implementation of Restrictions

Roles
1. Sales User
Restrictions -
Lead Creation: Create for all territories; lead auto-assigned to territory Sales Manager
Access Leads (with RW permissions): All created leads and assigned leads
Lead Owner: Should capture ID (preferably Email ID)
2. Ops User (Role doesn't exist, needs to be created)
Restrictions -
Lead Creation: Create for all territories; lead auto-assigned to territory Sales Manager
Access Leads (with RW permissions): All created leads and assigned leads
Lead Owner: Should capture ID (preferably Email ID)
3. Sales Manager
Restrictions -
Lead Creation: Create for all territories; lead auto-assigned to territory Sales Manager
Access Leads (with RW permissions): All created leads & leads belonging to assigned territory
Lead Owner: Should capture ID (preferably Email ID)
4. Ops Manager (Role doesn't exist, needs to be created)
Restrictions -
Lead Creation: Create for all territories; lead auto-assigned to territory Sales Manager
Access Leads (with RW permissions): All created leads & leads belonging to assigned territory
Lead Owner: Should capture ID (preferably Email ID)
5. Sales Master Manager
Restrictions -
Lead Creation: Create for all territories; lead auto-assigned to territory Sales Manager
Access Leads (with RW permissions): All created leads across territories
Lead Owner: Should capture ID (preferably Email ID)

The above implementation will make it free from employee designation; only 'owned by' and 'territory' fields of user need to be read.

Internally, as and when people log in to the system, roles will be assigned manually basis their designation and requirements.

**Comment by gaurav-naik** [comment]
Lead assignment scheme implemented as discussed over telephone:

Sales User: Assign to self.
Ops User: Assign to regional sales manager.

**Comment by AnandAmitabh** [comment]
1. Lead State in the New Lead form:
2 new options need to added - Wrong Number, Not a Sales Lead

2. When leads report is downloaded using the reports builder, the comments appear with HTML tags; needs to be changed to plain text

3. In the filters in Report Builder, currently AND logic applies when multiple filters are applied. Can this be modified to OR logic. Purpose: Lead reports for multiple lead owners can be downloaded with one search as against the current practice where separate filters need to be implemented, once for each lead owner

4. Date wise raw dump of leads is not extractable at present. Can this be implemented?

**Comment by gaurav-naik** [comment]
1. Options added to Lead State
2. Customization involved (TAT 1hr, require approval from @vickybiswas):
   1. Custom Field in Lead for plain text HTML.
   2. Code to extract plain text from HTML and place in field.

3. Can use existing filters `Lead Owner IN <user1 email id1>, <user2 email id>` for multiple lead owners. 
![awfis_lead_report_filters](https://cloud.githubusercontent.com/assets/17795124/21600931/b619e924-d1a9-11e6-8bec-1ace013bba3d.png)

4. Any specific format expected? Need clarification.

**Comment by vickybiswas** [comment]
Customization involved (TAT 1hr, require approval from @vickybiswas):
        Custom Field in Lead for plain text HTML.
        Code to extract plain text from HTML and place in field.
Approved not sure though if we need to really add a custom field here.

**Comment by AnandAmitabh** [comment]
1. Verified; working well

2. Vicky has already approved this; please go ahead with the changes

3. Thanks for the pointers :)

4. No format requirement as such; idea is that raw dump of all leads with all fields can be extracted

**Comment by AnandAmitabh** [comment]
Please add NA as Source option under Lead Channel - Call Centre
