### ISSUE TITLE
Updates to Lead Doctype

### ISSUE THREAD

**Issue by gaurav-naik** [mntechnique/awfis_erpnext#5]
@vickybiswas @anandamitabh

Outlining requirement w.r.t design document shared by Amitabh:
https://docs.google.com/spreadsheets/d/1HsTJBlVOMoa2Bk_ro1tF-HXAJ4fka20feBUqTCMAFd8/edit#gid=926839468

Tasks:

1. Add additional options in Channels field.
2. Add records under Source along with options.
3. Add new custom field Lead Sub Source with options.
4. Script to filter Channels, Source, Sub-source, as per new design document.

TAT: 2.00 - 2.25 hours. (Coding, data entry + testing)

**Comment by AnandAmitabh** [comment]
Lead Channel - Call Centre
Add new option under Source - Returning Customer

**Comment by gaurav-naik** [comment]
https://github.com/mntechnique/awfis_erpnext/releases/tag/v1.7.1

**Comment by gaurav-naik** [comment]
### Updated sources for existing channels and new Inbound channel:

Channel: **Call Center**
- Sources:
  - Returning Customer
  - N/A
  - Online (* standard cascade instead of adding social media in Sub-source for consistency)

Channel: **Inbound**  
- Sources: 
  - Email
    - contact@awfis.com
    - info@awfis.com
  - SEM
    - Social Media
    - Instant Office
    - Online Listing
  - <strike>Do not show campaigns for Inbound</strike>
  - Display campaigns only when source is Online
  
Channel: **Sales Team**
- Sources: 
  - Broker
    - International Property Consultant
    - Domestic Property Consultant
  - Hide Channel Partner field when Source is Broker

* Do not add sub-sources for SEM
* Set Channel as Inbound for SEM leads.

**Comment by AnandAmitabh** [comment]
For leads coming through landing pages, Source is correctly reflecting SEM; but Lead Channel is still showing Sales Team. SEM needs to be mapped to Lead Channel - Inbound. Please implement.

**Comment by gaurav-naik** [comment]
Fixed:
https://github.com/mntechnique/awfis_erpnext/commit/d75b5eec1943ea32c4eddf339891d930af494697

**Comment by AnandAmitabh** [comment]
Don't think the change is still implemented. PFA screenshot of test query I
created about 5 mins ago.

Please fix at the earliest, leads coming from the SEM channel are being
mapped incorrectly.

*Amitabh Anand*


Manager, Corporate Strategy



*Awfis Space Solution Pvt Ltd*

Cell : +91-813 052 2936

A-16, 1st Floor, Aruna Asaf Ali Marg,

Qutub Institutional Area, New Delhi - 110016

www.awfis.com






*Mumbai:* Churchgate, Lower Parel, Andheri (W), Powai, Andheri (E), Vashi
*NCR:* VasantKunj, South Ex, Connaught Place, Golf Course Road, Sector 44
Gurgaon
*Bengaluru:* IndiraNagar, Koramangala, MG Road, ORR, Hosur Road
*Hyderabad:* Banjara Hills

*Awfis Suites (1 to 4 pax Cabin) at Formule 1 Hotels at Gurgaon, Noida,
Pune, Hyderabad, Ahmedabad*

*Booking meeting rooms is as easy as booking a movie ticket !*

*Choose from a large network of meeting rooms of leading hotels and
Awfis Pro-Working centre*

**Comment by gaurav-naik** [comment]
Checking now.

**Comment by gaurav-naik** [comment]
Hi Amitabh,

The SEM lead channel issue has been fixed. Can you please confirm?

**Comment by AnandAmitabh** [comment]
Working fine. Thanks.

*Amitabh Anand*


Manager, Corporate Strategy



*Awfis Space Solution Pvt Ltd*

Cell : +91-813 052 2936

A-16, 1st Floor, Aruna Asaf Ali Marg,

Qutub Institutional Area, New Delhi - 110016

www.awfis.com






*Mumbai:* Churchgate, Lower Parel, Andheri (W), Powai, Andheri (E), Vashi
*NCR:* VasantKunj, South Ex, Connaught Place, Golf Course Road, Sector 44
Gurgaon
*Bengaluru:* IndiraNagar, Koramangala, MG Road, ORR, Hosur Road
*Hyderabad:* Banjara Hills

*Awfis Suites (1 to 4 pax Cabin) at Formule 1 Hotels at Gurgaon, Noida,
Pune, Hyderabad, Ahmedabad*

*Booking meeting rooms is as easy as booking a movie ticket !*

*Choose from a large network of meeting rooms of leading hotels and
Awfis Pro-Working centre*

**Comment by AnandAmitabh** [comment]
Fixes required:
1. Bangalore now has 2 Area Sales Manager (ERP role - Sales Manager). All new leads being entered into the system are being assigned to both; we want assignment to happen only to Abhishek Sharma; the other ASM is Mrinal Kumar
2. Mobile number field is not accepting ISD numbers; needs to be changed to accommodate the same

**Comment by gaurav-naik** [comment]
Tasks:
1. DND List for Lead in Awfis Settings Page
    - A list of users to whom Leads will not get assigned, which System Managers can edit.

2. Modify Validation for Mobile No field.

**ETA**: ~1 HR

@vickybiswas
